### ISSUE TITLE
Unclear how to create Edge Definitions

### ISSUE THREAD

**Issue by salines** [cloudhubke/sails-arangojs#2]
https://sails-arangojs.netlify.com/docs/createmodel#edge-definitions

Can you improve docs? How and where to put edgeDefinition?

`    edgeDefinition: {
      collection: 'user',
      from: ['pictures'],
      to: ['user'],
    },`

> The attribute `edgeDefinition` on the `pictures` model contains invalid properties. The property `from` isn't a recognized property.

**Comment by gaithoben** [comment]
The documentation is now fixed.
