### ISSUE TITLE
Does sails-arangojs support populate?

### ISSUE THREAD

**Issue by oneminute** [cloudhubke/sails-arangojs#6]
Hi!
    Does sails-arangojs support populate? I use sails-arangojs to populate child records, but I got an error:

> Error: Consistency violation: Provided "stage 1 query" contains extraneous top-level keys: populates

My codes:
```
var records = await Device.find({id: device.id}).populate('category');
```

Thanks.

**Comment by gaithoben** [comment]
No. This feature in not supported. ArangoDb is not a relational DB but you can check INBOUND and OUTBOUND vertices.
